---
title: "R_bio_workflow"
author: "Joe"
date: "`2024-10-11`"
output: 
  html_document:
    df_print: paged
  pdf_document:
    includes:
      in_header: header.tex
    latex_engine: xelatex
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## TCGA数据整理_TPM文件

```{r TCGA_TPM_data, message=TRUE, warning=TRUE, include=FALSE}
#加载R包
library(rjson)
library(tidyverse)
#设置路径
setwd("E:/CRC")
#CART文件名字
cart_file <- "gdc_download_20240814_054206.318162"
#json文件名字
json_file <- "metadata.cart.2024-08-14.json"
#读入meta.data文件
json <- jsonlite::fromJSON(json_file)
#View(json)
#获取样本名称及文件名称
sample_id <- sapply(json$associated_entities,function(x){x[,1]})
#sample_id[1:10]
file_sample <- data.frame(sample_id,file_name=json$file_name)  
#View(file_sample)
#获取counts所在位置
count_file <- list.files(paste0(cart_file,'/',sep=''),
                         pattern = '*.tsv',recursive = TRUE)
#count_file[1:10]
#获取每个文件名称
count_file_name <- strsplit(count_file,split='/')
#count_file_name[1:10]
count_file_name <- sapply(count_file_name,function(x){x[2]})
#count_file_name[1:10]
#构建一个空的数据框
matrix = data.frame(matrix(nrow=60660,ncol=0))
#逐个读取及合并
for (i in 1:length(count_file)){
  path = paste0(cart_file,'//',count_file[i])   #Counts文件夹名
  data<- read.delim(path,fill = TRUE,header = FALSE,row.names = 1)
  colnames(data)<-data[2,]
  data <-data[-c(1:6),]
  #3：unstranded,counts；4：stranded_first；5：stranded_second；6：tpm_unstranded；7：fpkm_unstranded；8：fpkm_uq_unstranded
  #data <- data[3]
  data <- data[6]
  #data <- data[7]
  colnames(data) <- file_sample$sample_id[which(file_sample$file_name==count_file_name[i])]
  matrix <- cbind(matrix,data)
}
#转化为gene_symbol
path = paste0(cart_file,'//',count_file[1])
data<- as.matrix(read.delim(path,fill = TRUE,header = FALSE,row.names = 1))
gene_name <-data[-c(1:6),1]
#gene_name[1:10]
matrix0 <- cbind(gene_name,matrix)
#获取基因类型
gene_type <- data[-c(1:6),2]
#gene_type[1:10]
matrix0 <- cbind(gene_type,matrix0)
#将gene_name列去除重复的基因，保留基因最大表达量结果,min,mean
matrix0 <- aggregate( . ~ gene_name,data=matrix0, max)
table(gene_name)
#保留mRNA
matrix0 <- subset(x = matrix0, gene_type == "protein_coding")
#table(gene_type)
#将gene_name列设为行名，并转化为导出格式
rownames(matrix0) <- matrix0[,1]
matrix0 <- matrix0[,-c(1,2)]
matrix1 = data.frame(ID=rownames(matrix0),matrix0)
colnames(matrix1) = gsub('[.]', '-', colnames(matrix1))
#导出
write.table(matrix1,'TCGA_CRC_TPM.txt', sep="\t", quote=F, row.names = F)
#write.table(matrix1,'TCGA_LUSC_count.txt', sep="\t", quote=F, row.names = F)
```

## TCGA数据整理_COUNT文件

```{r TCGA_COUNT_data, message=TRUE, warning=TRUE, include=FALSE}
#加载R包
library(rjson)
library(tidyverse)
#设置路径
setwd("E:/CRC")
#CART文件名字
cart_file <- "gdc_download_20240814_054206.318162"
#json文件名字
json_file <- "metadata.cart.2024-08-14.json"
#读入meta.data文件
#出现报错，注意上面的包是否加载，工作目录下是否存在这个文件，文件是否损坏（先跑示例数据）
json <- jsonlite::fromJSON(json_file)
#View(json)
#获取样本名称及文件名称
sample_id <- sapply(json$associated_entities,function(x){x[,1]})
#sample_id[1:10]
file_sample <- data.frame(sample_id,file_name=json$file_name)  
#View(file_sample)
#获取counts所在位置
count_file <- list.files(paste0(cart_file,'/',sep=''),
                         pattern = '*.tsv',recursive = TRUE)
#count_file[1:10]
#获取每个文件名称
count_file_name <- strsplit(count_file,split='/')
#count_file_name[1:10]
count_file_name <- sapply(count_file_name,function(x){x[2]})
#count_file_name[1:10]
#构建一个空的数据框
matrix = data.frame(matrix(nrow=60660,ncol=0))
#逐个读取及合并
#出现报错，注意解压方式（仔细看视频），文件名修改，文件后缀（解压软件）
for (i in 1:length(count_file)){
  path = paste0(cart_file,'//',count_file[i])   #Counts文件夹名
  data<- read.delim(path,fill = TRUE,header = FALSE,row.names = 1)
  colnames(data)<-data[2,]
  data <-data[-c(1:6),]
  #3：unstranded,counts；4：stranded_first；5：stranded_second；6：tpm_unstranded；7：fpkm_unstranded；8：fpkm_uq_unstranded
  #data <- data[3]
  data <- data[3]
  #data <- data[7]
  colnames(data) <- file_sample$sample_id[which(file_sample$file_name==count_file_name[i])]
  matrix <- cbind(matrix,data)
}
#转化为gene_symbol
path = paste0(cart_file,'//',count_file[1])
data<- as.matrix(read.delim(path,fill = TRUE,header = FALSE,row.names = 1))
gene_name <-data[-c(1:6),1]
#gene_name[1:10]
matrix0 <- cbind(gene_name,matrix)
#获取基因类型
gene_type <- data[-c(1:6),2]
#gene_type[1:10]
matrix0 <- cbind(gene_type,matrix0)
#将gene_name列去除重复的基因，保留基因最大表达量结果,min,mean
matrix0 <- aggregate( . ~ gene_name,data=matrix0, max)
table(gene_name)
#保留mRNA
matrix0 <- subset(x = matrix0, gene_type == "protein_coding")
#table(gene_type)
#将gene_name列设为行名，并转化为导出格式
rownames(matrix0) <- matrix0[,1]
matrix0 <- matrix0[,-c(1,2)]
matrix1 = data.frame(ID=rownames(matrix0),matrix0)
colnames(matrix1) = gsub('[.]', '-', colnames(matrix1))
#导出
#write.table(matrix1,'TCGA_CORD_TPM.txt', sep="\t", quote=F, row.names = F)
write.table(matrix1,'TCGA_CRC_count.txt', sep="\t", quote=F, row.names = F)
```


##获取数据基因
##通过KEGGREST包获取部分相关基因

```{r get_genes, message=TRUE, warning=TRUE, include=FALSE}
setwd("E:/基因建模/gene/KEGG")

library(KEGGREST)

# 定义路径
pathways <- c('hsa04370','hsa04151','hsa04010','hsa04330','hsa04350','hsa04310')

# 初始化一个空的数据框用于存储所有基因信息
all_genes <- data.frame()

# 遍历每个通路
for (pathway_id in pathways) {
  # 获取通路信息
  pathway_info <- keggGet(pathway_id)
  
  # 提取基因信息
  genes <- unlist(lapply(gs[[1]]$GENE, function(x) strsplit(x, ";")[[1]]))
  
  genelist <- genes[which((seq_along(genes) %% 3) == 2)]
  
  # 将基因信息转换为数据框
  genelist <-  data.frame(genelist)
  
  # 合并到总的数据框中
  all_genes <- rbind(all_genes, genelist)
}

# 去除重复的基因
all_genes <- unique(all_genes)

# 输出到CSV文件
write.table(all_genes, "genelist.csv", row.names = FALSE, col.names = TRUE, sep = ",", quote = FALSE)
```

## TCGA临床信息整理

```{r message=TRUE, warning=TRUE, include=FALSE}
#加载包
library("XML")
library("methods")
library("tinyarray")
#设置路径
setwd("E:/CRC")
#设置一个目录
dir="E:/CRC/gdc_download_20240814_142022.604604"
#获取每个样本所在位置
all_fiels=list.files(path = dir ,pattern='*.xml$',recursive=T)##导入文件
cl = lapply(all_fiels, function(x){
  #读取 XML 文件  
  result <- xmlParse(file = file.path(dir,x)) 
  #获取根元素
  rootnode <- xmlRoot(result)  
  #转化为数据框
  xmldataframe <- xmlToDataFrame( rootnode[2] ) 
  #转置
  return(t(xmldataframe)) })

#由于读入的时候自动读入了一些NA值，导致存在不同的列
#因此获取共有列来保持列数相同
n = intersect_all(lapply(cl, rownames))
#提取共有列
cl3 = lapply(cl, function(x){x[n,]})
#对每个列表进行合并
clinical <- t(do.call(cbind,cl3))
#导出
# 将第12列(TCGA样本编号列)设置为行名
rownames(clinical) <- clinical[, 12]
# 从数据框中移除第十二列
#clinical <- clinical[, -12]
#导出
write.table(clinical,file="clinical.txt",sep="\t",quote=F,row.names = F)
```

## TCGA差异基因分析_Wilcoxon

```{r Differential_gene_analysis_Wilcoxon, message=TRUE, warning=TRUE, include=FALSE}
library(limma)
library(pheatmap)
library(stringr)
library(ggplot2)
library(ggVolcano)
#设置路径
setwd("E:/CRC")
#TPM文件使用Wilcoxon
#读取输入文件
data=read.table("TCGA_CRC_TPM.txt", header=T, sep="\t", check.names=F,row.names = 1)
#转化为matrix
dimnames=list(rownames(data), colnames(data))
data=matrix(as.numeric(as.matrix(data)), nrow=nrow(data), dimnames=dimnames)
#去除低表达的基因
data=data[rowMeans(data)>1,]
#正常和肿瘤数目,第14,15字符,01-09是癌症，10-19是正常，20-29是癌旁
group=sapply(strsplit(colnames(data),"\\-"), "[", 4)
group=sapply(strsplit(group,""), "[", 1)
#将2变为1
group=gsub("2", "1", group)
view(group)
#统计group中0和1的数量
table(group)
#获取正常及肿瘤组样本数目
conNum=length(group[group==1])
treatNum=length(group[group==0])
Type=c(rep(1,conNum), rep(2,treatNum))
#根据正常和肿瘤排序
data1 = data[,group == 1]
data2 = data[,group == 0]
data = cbind(data1,data2)
#差异分析
outTab=data.frame()
for(i in row.names(data)){
  rt=data.frame(expression=data[i,], Type=Type)
  wilcoxTest=wilcox.test(expression ~ Type, data=rt)
  pvalue=wilcoxTest$p.value
  conGeneMeans=mean(data[i,1:conNum])
  treatGeneMeans=mean(data[i,(conNum+1):ncol(data)])
  logFC=log2(treatGeneMeans)-log2(conGeneMeans)
  conMed=median(data[i,1:conNum])
  treatMed=median(data[i,(conNum+1):ncol(data)])
  diffMed=treatMed-conMed
  if( ((logFC>0) & (diffMed>0)) | ((logFC<0) & (diffMed<0)) ){
    outTab=rbind(outTab,cbind(gene=i,conMean=conGeneMeans,treatMean=treatGeneMeans,logFC=logFC,pValue=pvalue))}
}
pValue=outTab[,"pValue"]
fdr=p.adjust(as.numeric(as.vector(pValue)), method="fdr")
outTab=cbind(outTab, fdr=fdr)
write.table(outTab,file="TCGA.all.Wilcoxon.txt",sep="\t",row.names=F,quote=F)
logFCfilter=1
fdrFilter=0.05
#输出差异基因
outDiff=outTab[( abs(as.numeric(as.vector(outTab$logFC)))>logFCfilter & 
                   as.numeric(as.vector(outTab$fdr))<fdrFilter),]
write.table(outDiff,file="TCGA.diff.Wilcoxon.txt",sep="\t",row.names=F,quote=F)
outTab$logFC=as.numeric(as.vector(outTab$logFC))
outTab$change = ifelse(outTab$fdr < 0.05 & abs(outTab$logFC) >= 1, 
                       ifelse(outTab$logFC> 1 ,'Up','Down'),
                       'Stable')
#热图
#设置展示基因的数目
geneNum=50
outDiff=outDiff[order(as.numeric(as.vector(outDiff$logFC))),]
diffGeneName=as.vector(outDiff[,1])
diffLength=length(diffGeneName)
hmGene=c()
if(diffLength>(2*geneNum)){
  hmGene=diffGeneName[c(1:geneNum,(diffLength-geneNum+1):diffLength)]
}else{
  hmGene=diffGeneName
}
hmExp=log2(data[hmGene,]+0.01)
Type=c(rep("Normal",conNum),rep("Tumor",treatNum))
names(Type)=colnames(data)
Type=as.data.frame(Type)
#pdf(file="heatmap_CRC_Top50.pdf", width=10, height=8)
png("heatmap_CRC_Wilcoxon_Top50.png", width=10, height=8, units = "in", res = 800)
pheatmap(hmExp, 
         annotation=Type, 
         color = colorRampPalette(c(rep("blue",5), "white", rep("red",5)))(50),
         cluster_cols =F,
         show_colnames = F,
         scale="row",
         fontsize = 8,
         fontsize_row=5,
         fontsize_col=8)
dev.off()
#火山图2,可以显示希望标记的基因,例：TUBA1C
geneList0 <- c('NELL2',"NKX2-2","HPCAL4")
for (i in geneList0) {
  geneList <- outTab[i,]
  rownames(outTab) <- outTab$gene
  sum(is.na(outTab$logFC))  # 检查 logFC 列中有多少个 NA 值
  sum(is.na(outTab$fdr))    # 检查 fdr 列中有多少个 NA 值
  sum(is.na(outTab$change)) # 检查 change 列中有多少个 NA 值
  outTab$logFC[is.na(outTab$logFC)] <- 0  # 将 logFC 列中的 NA 值替换为 0
  outTab$fdr[is.na(outTab$fdr)] <- 1      # 将 fdr 列中的 NA 值替换为 1
  outTab <- na.omit(outTab)
  p <- ggplot(# 数据、映射、颜色
    outTab, aes(x = logFC, y = -log10(fdr), colour=change)) +
    geom_point(alpha=0.5, size=3.5) +
    scale_color_manual(values=c("#546de5","#d2dae2","#ff4757"))+
    #突出表示差异基因
    geom_point(data=geneList,aes(x = logFC, y = -log10(fdr)),colour="yellow",size=3.5)+
    #辅助线
    geom_vline(xintercept=c(-1,1),lty=3,col="black",lwd=0.8) +
    geom_hline(yintercept = -log10(0.05),lty=3,col="black",lwd=0.8) +
    labs(x="log2(fold change)",y="-log10 (p-value)")+   # 坐标轴# 坐标轴和图标题title="Volcano plot",
    theme_bw()+    #去除背景色
    theme(panel.grid = element_blank())+  #去除网格线
    #xlim(-2, 2)+   #设置坐标轴范围
    #图例
    theme(plot.title = element_text(hjust = 0.5,size=24), 
          legend.position="bottom", 
          legend.title = element_blank(),
          legend.text=element_text(size=18),
          legend.key.size = unit(1, 'cm'),
          legend.background = element_rect(fill="gray90", linetype="solid",colour ="gray"),
          axis.title.x =element_text(size=18), 
          axis.title.y=element_text(size=18),
          axis.text=element_text(size=14,face = "bold"))
  #标记出选定基因的label
  geneList1 <- outTab[rownames(outTab) %in% i,]
  geneList1 <- subset(geneList1, select = -change)
  geneList1$label <- rownames(geneList1)
  #pdf("hotplot.pdf", width = 8, height = 10)
  volplot <- p + geom_label_repel(data = geneList1, 
                       aes(x = logFC, y = -log10(fdr), label = label),
                       size = 4,color="black",
                       box.padding = unit(0.4, "lines"), 
                       segment.color = "black",   #连线的颜色
                       segment.size = 0.4,  #连线的粗细
  )
  png(paste("volcano_Wilcoxon_",i,".png"), width = 8, height = 10, units = "in", res = 800)
  print(volplot)
  dev.off()
}

```

## TCGA差异基因分析_limma

```{r Differential_gene_analysis_limma, message=TRUE, warning=TRUE, include=FALSE}
#加载包
library(limma)
library(pheatmap)
library(stringr)
library(edgeR)
library(ggrepel)
#设置工作目录
setwd("E:/CRC")
#读取输入文件
data=read.table("TCGA_CRC_count.txt", header=T, sep="\t", check.names=F,row.names = 1)
#转化为matrix
dimnames=list(rownames(data), colnames(data))
data=matrix(as.numeric(as.matrix(data)), nrow=nrow(data), dimnames=dimnames)
#去除低表达的基因
data=data[rowMeans(data)>1,]
#正常和肿瘤数目,第14,15字符,01-09是癌症，10-19是正常，20-29是癌旁
group=sapply(strsplit(colnames(data),"\\-"), "[", 4)
group=sapply(strsplit(group,""), "[", 1)
#将2变为1
group=gsub("2", "1", group)
#获取正常及肿瘤组样本数目
conNum=length(group[group==1])
treatNum=length(group[group==0])
Type=c(rep(1,conNum), rep(2,treatNum))
#根据正常和肿瘤排序
data1 = data[,group == 1]
data2 = data[,group == 0]
data = cbind(data1,data2)
#设置分组信息
Type = factor(Type)
design <- model.matrix(~0+Type)
rownames(design) = colnames(data)
colnames(design) <- levels(Type)
#创建对象
DGElist <- DGEList( counts = data, group = Type )
#过滤掉cpm小于等于1的基因
keep_gene <- rowSums( cpm(DGElist) > 1 ) >= 2 # 自定义
table(keep_gene)
#生成DGEList对象
DGElist <- DGElist[keep_gene, , keep.lib.sizes = FALSE ]
#计算比例因子以将原始库大小转换为有效库大小。
DGElist <- calcNormFactors( DGElist )
#转换logCPM
v <- voom(DGElist, design, plot = TRUE, normalize = "quantile")
#非线性最小二乘法
fit <- lmFit(v, design)
colnames(design)=c("normal","tumor")
#构建比较矩阵
cont.matrix <- makeContrasts(contrasts = c('tumor-normal'), levels = design)
#线性拟合模型构建
fit2 <- contrasts.fit(fit, cont.matrix)
#用经验贝叶斯调整t-test中方差的部分
fit2 <- eBayes(fit2)
nrDEG_limma_voom = topTable(fit2, coef = 'tumor-normal', n = Inf)
nrDEG_limma_voom = na.omit(nrDEG_limma_voom)
head(nrDEG_limma_voom)
#保存全部计算的基因
nrDEG_limma_voom$gene <- rownames(nrDEG_limma_voom)

write.table(nrDEG_limma_voom,file="TCGA.all.limma.txt",sep="\t",row.names=F,quote=F)
#筛选标准
padj = 0.05
logFC = 1
#筛选
outDiff = nrDEG_limma_voom[(nrDEG_limma_voom$adj.P.Val < padj &
                              (nrDEG_limma_voom$logFC>logFC | nrDEG_limma_voom$logFC<(-logFC))),]
outDiff = outDiff[order(outDiff$logFC),]
write.table(data.frame(ID=rownames(outDiff),outDiff),file="TCGA.diff.limma.txt",sep="\t",row.names=F,quote=F)
nrDEG_limma_voom$logFC=as.numeric(as.vector(nrDEG_limma_voom$logFC))
nrDEG_limma_voom$change = ifelse(nrDEG_limma_voom$adj.P.Val < 0.05 & abs(nrDEG_limma_voom$logFC) >= 1, 
                       ifelse(nrDEG_limma_voom$logFC> 1 ,'Up','Down'),
                       'Stable')
#热图
#设置展示基因的数目
geneNum=50
outDiff=outDiff[order(as.numeric(as.vector(outDiff$logFC))),]
diffGeneName=as.vector(outDiff[,7])
diffLength=length(diffGeneName)
hmGene=c()
if(diffLength>(2*geneNum)){
  hmGene=diffGeneName[c(1:geneNum,(diffLength-geneNum+1):diffLength)]
}else{
  hmGene=diffGeneName
}
hmExp=log2(data[hmGene,]+0.01)
Type=c(rep("Normal",conNum),rep("Tumor",treatNum))
names(Type)=colnames(data)
Type=as.data.frame(Type)
#pdf(file="heatmap_CRC_Top50.pdf", width=10, height=8)
png("heatmap_CRC_limma_Top50.png", width=10, height=8, units = "in", res = 800)
pheatmap(hmExp, 
         annotation=Type, 
         color = colorRampPalette(c(rep("blue",5), "white", rep("red",5)))(50),
         cluster_cols =F,
         show_colnames = F,
         scale="row",
         fontsize = 8,
         fontsize_row=5,
         fontsize_col=8)
dev.off()
#火山图2,可以显示希望标记的基因,例：TUBA1C
geneList0 <- c('NELL2',"NKX2-2","HPCAL4")
for (i in geneList0) {
  geneList <- nrDEG_limma_voom[i,]
  rownames(nrDEG_limma_voom) <- nrDEG_limma_voom$gene
  sum(is.na(nrDEG_limma_voom$logFC))  # 检查 logFC 列中有多少个 NA 值
  sum(is.na(nrDEG_limma_voom$adj.P.Val))    # 检查 adj.P.Val 列中有多少个 NA 值
  sum(is.na(nrDEG_limma_voom$change)) # 检查 change 列中有多少个 NA 值
  nrDEG_limma_voom$logFC[is.na(nrDEG_limma_voom$logFC)] <- 0  # 将 logFC 列中的 NA 值替换为 0
  nrDEG_limma_voom$adj.P.Val[is.na(nrDEG_limma_voom$adj.P.Val)] <- 1      # 将 adj.P.Val 列中的 NA 值替换为 1
  nrDEG_limma_voom <- na.omit(nrDEG_limma_voom)
  p <- ggplot(# 数据、映射、颜色
    nrDEG_limma_voom, aes(x = logFC, y = -log10(adj.P.Val), colour=change)) +
    geom_point(alpha=0.5, size=3.5) +
    scale_color_manual(values=c("#546de5","#d2dae2","#ff4757"))+
    #突出表示差异基因
    geom_point(data=geneList,aes(x = logFC, y = -log10(adj.P.Val)),colour="yellow",size=3.5)+
    #辅助线
    geom_vline(xintercept=c(-1,1),lty=3,col="black",lwd=0.8) +
    geom_hline(yintercept = -log10(0.05),lty=3,col="black",lwd=0.8) +
    labs(x="log2(fold change)",y="-log10 (p-value)")+   # 坐标轴# 坐标轴和图标题title="Volcano plot",
    theme_bw()+    #去除背景色
    theme(panel.grid = element_blank())+  #去除网格线
    #xlim(-2, 2)+   #设置坐标轴范围
    #图例
    theme(plot.title = element_text(hjust = 0.5,size=24), 
          legend.position="bottom", 
          legend.title = element_blank(),
          legend.text=element_text(size=18),
          legend.key.size = unit(1, 'cm'),
          legend.background = element_rect(fill="gray90", linetype="solid",colour ="gray"),
          axis.title.x =element_text(size=18), 
          axis.title.y=element_text(size=18),
          axis.text=element_text(size=14,face = "bold"))
  #标记出选定基因的label
  geneList1 <- nrDEG_limma_voom[rownames(nrDEG_limma_voom) %in% i,]
  geneList1 <- subset(geneList1, select = -change)
  geneList1$label <- rownames(geneList1)
  #pdf("hotplot.pdf", width = 8, height = 10)
  volplot <- p + geom_label_repel(data = geneList1, 
                       aes(x = logFC, y = -log10(adj.P.Val), label = label),
                       size = 4,color="black",
                       box.padding = unit(0.4, "lines"), 
                       segment.color = "black",   #连线的颜色
                       segment.size = 0.4,  #连线的粗细
  )
  png(paste("volcano_limma_",i,".png"), width = 8, height = 10, units = "in", res = 800)
  print(volplot)
  dev.off()
}
```

## TCGA差异基因分析_edgeR

```{r Differential_gene_analysis_edgeR, message=TRUE, warning=TRUE, include=FALSE}
#加载包
library(limma)
library(pheatmap)
library(stringr)
library(edgeR)
#设置工作目录
setwd("E:/CRC")
#读取输入文件
data=read.table("TCGA_CRC_count.txt", header=T, sep="\t", check.names=F,row.names = 1)
#转化为matrix
dimnames=list(rownames(data), colnames(data))
data=matrix(as.numeric(as.matrix(data)), nrow=nrow(data), dimnames=dimnames)
#去除低表达的基因
data=data[rowMeans(data)>1,]
#正常和肿瘤数目,第14,15字符,01-09是癌症，10-19是正常，20-29是癌旁
group=sapply(strsplit(colnames(data),"\\-"), "[", 4)
group=sapply(strsplit(group,""), "[", 1)
#将2变为1
group=gsub("2", "1", group)
#获取正常及肿瘤组样本数目
conNum=length(group[group==1])
treatNum=length(group[group==0])
Type=c(rep(1,conNum), rep(2,treatNum))
#根据正常和肿瘤排序
data1 = data[,group == 1]
data2 = data[,group == 0]
data = cbind(data1,data2)
#分组矩阵
Type = factor(Type)
design <- model.matrix(~0+Type)
rownames(design) = colnames(data)
colnames(design) <- levels(Type)
#差异表达矩阵
DGElist <- DGEList( counts = data, group = Type)
keep_gene <- rowSums( cpm(DGElist) > 1 ) >= 2 ## 自定义
table(keep_gene)
DGElist <- DGElist[ keep_gene, , keep.lib.sizes = FALSE ]
DGElist <- calcNormFactors( DGElist )
DGElist <- estimateGLMCommonDisp(DGElist, design)
DGElist <- estimateGLMTrendedDisp(DGElist, design)
DGElist <- estimateGLMTagwiseDisp(DGElist, design)
fit <- glmFit(DGElist, design)
results <- glmLRT(fit, contrast = c(-1, 1))
nrDEG_edgeR <- topTags(results, n = nrow(DGElist))
nrDEG_edgeR <- as.data.frame(nrDEG_edgeR)
head(nrDEG_edgeR)
#筛选
padj = 0.05
logFC= 1
outdiff  = nrDEG_edgeR[(nrDEG_edgeR$FDR < padj &
                          (nrDEG_edgeR$logFC>logFC | nrDEG_edgeR$logFC<(-logFC))),]
write.table(data.frame(ID=rownames(outdiff),outdiff),file="TCGA.diff.edgeR.txt",sep="\t",row.names=F,quote=F)
nrDEG_edgeR$gene <- rownames(nrDEG_edgeR)
nrDEG_edgeR$logFC=as.numeric(as.vector(nrDEG_edgeR$logFC))
nrDEG_edgeR$change = ifelse(nrDEG_edgeR$FDR < 0.05 & abs(nrDEG_edgeR$logFC) >= 1, 
                       ifelse(nrDEG_edgeR$logFC> 1 ,'Up','Down'),
                       'Stable')
#热图
#设置展示基因的数目
geneNum=50
outDiff$gene <- rownames(outDiff)
outDiff=outDiff[order(as.numeric(as.vector(outDiff$logFC))),]
diffGeneName=as.vector(outDiff[,6])
diffLength=length(diffGeneName)
hmGene=c()
if(diffLength>(2*geneNum)){
  hmGene=diffGeneName[c(1:geneNum,(diffLength-geneNum+1):diffLength)]
}else{
  hmGene=diffGeneName
}
hmExp=log2(data[hmGene,]+0.01)
Type=c(rep("Normal",conNum),rep("Tumor",treatNum))
names(Type)=colnames(data)
Type=as.data.frame(Type)
#pdf(file="heatmap_CRC_Top50.pdf", width=10, height=8)
png("heatmap_CRC_edgeR_Top50.png", width=10, height=8, units = "in", res = 800)
pheatmap(hmExp, 
         annotation=Type, 
         color = colorRampPalette(c(rep("blue",5), "white", rep("red",5)))(50),
         cluster_cols =F,
         show_colnames = F,
         scale="row",
         fontsize = 8,
         fontsize_row=5,
         fontsize_col=8)
dev.off()
#火山图2,可以显示希望标记的基因,例：TUBA1C
geneList0 <- c('NELL2',"NKX2-2","HPCAL4")
for (i in geneList0) {
  geneList <- nrDEG_edgeR[i,]
  rownames(nrDEG_edgeR) <- nrDEG_edgeR$gene
  sum(is.na(nrDEG_edgeR$logFC))  # 检查 logFC 列中有多少个 NA 值
  sum(is.na(nrDEG_edgeR$FDR))    # 检查 FDR 列中有多少个 NA 值
  sum(is.na(nrDEG_edgeR$change)) # 检查 change 列中有多少个 NA 值
  nrDEG_edgeR$logFC[is.na(nrDEG_edgeR$logFC)] <- 0  # 将 logFC 列中的 NA 值替换为 0
  nrDEG_edgeR$FDR[is.na(nrDEG_edgeR$FDR)] <- 1      # 将 FDR 列中的 NA 值替换为 1
  nrDEG_edgeR <- na.omit(nrDEG_edgeR)
  p <- ggplot(# 数据、映射、颜色
    nrDEG_edgeR, aes(x = logFC, y = -log10(FDR), colour=change)) +
    geom_point(alpha=0.5, size=3.5) +
    scale_color_manual(values=c("#546de5","#d2dae2","#ff4757"))+
    #突出表示差异基因
    geom_point(data=geneList,aes(x = logFC, y = -log10(FDR)),colour="yellow",size=3.5)+
    #辅助线
    geom_vline(xintercept=c(-1,1),lty=3,col="black",lwd=0.8) +
    geom_hline(yintercept = -log10(0.05),lty=3,col="black",lwd=0.8) +
    labs(x="log2(fold change)",y="-log10 (p-value)")+   # 坐标轴# 坐标轴和图标题title="Volcano plot",
    theme_bw()+    #去除背景色
    theme(panel.grid = element_blank())+  #去除网格线
    #xlim(-2, 2)+   #设置坐标轴范围
    #图例
    theme(plot.title = element_text(hjust = 0.5,size=24), 
          legend.position="bottom", 
          legend.title = element_blank(),
          legend.text=element_text(size=18),
          legend.key.size = unit(1, 'cm'),
          legend.background = element_rect(fill="gray90", linetype="solid",colour ="gray"),
          axis.title.x =element_text(size=18), 
          axis.title.y=element_text(size=18),
          axis.text=element_text(size=14,face = "bold"))
  #标记出选定基因的label
  geneList1 <- nrDEG_edgeR[rownames(nrDEG_edgeR) %in% i,]
  geneList1 <- subset(geneList1, select = -change)
  geneList1$label <- rownames(geneList1)
  #pdf("hotplot.pdf", width = 8, height = 10)
  volplot <- p + geom_label_repel(data = geneList1, 
                       aes(x = logFC, y = -log10(FDR), label = label),
                       size = 4,color="black",
                       box.padding = unit(0.4, "lines"), 
                       segment.color = "black",   #连线的颜色
                       segment.size = 0.4,  #连线的粗细
  )
  png(paste("volcano_edgeR_",i,".png"), width = 8, height = 10, units = "in", res = 800)
  print(volplot)
  dev.off()
}
```

## TCGA差异基因分析_DESeq2

```{r Differential_gene_analysis_DESeq2}
#加载包
library(limma)
library(pheatmap)
library(stringr)
library(DESeq2)
#设置工作目录
setwd("E:/CRC")
#读取输入文件
data=read.table("TCGA_CRC_count.txt", header=T, sep="\t", check.names=F,row.names = 1)
#转化为matrix
dimnames=list(rownames(data), colnames(data))
data=matrix(as.numeric(as.matrix(data)), nrow=nrow(data), dimnames=dimnames)
#去除低表达的基因
data=data[rowMeans(data)>1,]
#正常和肿瘤数目,第14,15字符,01-09是癌症，10-19是正常，20-29是癌旁
group=sapply(strsplit(colnames(data),"\\-"), "[", 4)
group=sapply(strsplit(group,""), "[", 1)
#将2变为1
group=gsub("2", "1", group)
#获取正常及肿瘤组样本数目
conNum=length(group[group==1])
treatNum=length(group[group==0])
Type=c(rep(1,conNum), rep(2,treatNum))
#根据正常和肿瘤排序
data1 = data[,group == 1]
data2 = data[,group == 0]
data = cbind(data1,data2)
#分组矩阵
condition = factor(Type)
coldata <- data.frame(row.names = colnames(data), condition)
dds <- DESeqDataSetFromMatrix(countData = data,
                              colData = coldata,
                              design = ~condition)
View(dds)
dds$condition
# 指定哪一组作为对照组
dds$condition<- relevel(dds$condition, ref = "1")
#差异表达矩阵
dds <- DESeq(dds)
allDEG2 <- as.data.frame(results(dds))
#筛选
padj = 0.05
logFC= 1
outdiff = allDEG2[(allDEG2$padj < padj &
                     (allDEG2$log2FoldChange>logFC | allDEG2$log2FoldChange<(-logFC))),]
write.table(data.frame(ID=rownames(outdiff),outdiff),file="TCGA.diff.DESeq2.txt",sep="\t",row.names=F,quote=F)
allDEG2$gene <- rownames(allDEG2)
allDEG2$log2FoldChange=as.numeric(as.vector(allDEG2$log2FoldChange))
allDEG2$change = ifelse(allDEG2$padj < 0.05 & abs(allDEG2$log2FoldChange) >= 1, 
                       ifelse(allDEG2$log2FoldChange> 1 ,'Up','Down'),
                       'Stable')
#热图
#设置展示基因的数目
geneNum=50
outdiff$gene <- rownames(outdiff)
outdiff=outdiff[order(as.numeric(as.vector(outdiff$logFC))),]
diffGeneName=as.vector(outdiff[,7])
diffLength=length(diffGeneName)
hmGene=c()
if(diffLength>(2*geneNum)){
  hmGene=diffGeneName[c(1:geneNum,(diffLength-geneNum+1):diffLength)]
}else{
  hmGene=diffGeneName
}
hmExp=log2(data[hmGene,]+0.01)
Type=c(rep("Normal",conNum),rep("Tumor",treatNum))
names(Type)=colnames(data)
Type=as.data.frame(Type)
#pdf(file="heatmap_CRC_Top50.pdf", width=10, height=8)
png("heatmap_CRC_DESeq2_Top50.png", width=10, height=8, units = "in", res = 800)
pheatmap(hmExp, 
         annotation=Type, 
         color = colorRampPalette(c(rep("blue",5), "white", rep("red",5)))(50),
         cluster_cols =F,
         show_colnames = F,
         scale="row",
         fontsize = 8,
         fontsize_row=5,
         fontsize_col=8)
dev.off()
#火山图2,可以显示希望标记的基因,例：TUBA1C
geneList0 <- c('NELL2',"NKX2-2","HPCAL4")
for (i in geneList0) {
  geneList <- allDEG2[i,]
  rownames(allDEG2) <- allDEG2$gene
  sum(is.na(allDEG2$log2FoldChange))  # 检查 log2FoldChange 列中有多少个 NA 值
  sum(is.na(allDEG2$padj))    # 检查 padj 列中有多少个 NA 值
  sum(is.na(allDEG2$change)) # 检查 change 列中有多少个 NA 值
  allDEG2$log2FoldChange[is.na(allDEG2$log2FoldChange)] <- 0  # 将 log2FoldChange 列中的 NA 值替换为 0
  allDEG2$padj[is.na(allDEG2$padj)] <- 1      # 将 padj 列中的 NA 值替换为 1
  allDEG2 <- na.omit(allDEG2)
  p <- ggplot(# 数据、映射、颜色
    allDEG2, aes(x = log2FoldChange, y = -log10(padj), colour=change)) +
    geom_point(alpha=0.5, size=3.5) +
    scale_color_manual(values=c("#546de5","#d2dae2","#ff4757"))+
    #突出表示差异基因
    geom_point(data=geneList,aes(x = log2FoldChange, y = -log10(padj)),colour="yellow",size=3.5)+
    #辅助线
    geom_vline(xintercept=c(-1,1),lty=3,col="black",lwd=0.8) +
    geom_hline(yintercept = -log10(0.05),lty=3,col="black",lwd=0.8) +
    labs(x="log2(fold change)",y="-log10 (p-value)")+   # 坐标轴# 坐标轴和图标题title="Volcano plot",
    theme_bw()+    #去除背景色
    theme(panel.grid = element_blank())+  #去除网格线
    #xlim(-2, 2)+   #设置坐标轴范围
    #图例
    theme(plot.title = element_text(hjust = 0.5,size=24), 
          legend.position="bottom", 
          legend.title = element_blank(),
          legend.text=element_text(size=18),
          legend.key.size = unit(1, 'cm'),
          legend.background = element_rect(fill="gray90", linetype="solid",colour ="gray"),
          axis.title.x =element_text(size=18), 
          axis.title.y=element_text(size=18),
          axis.text=element_text(size=14,face = "bold"))
  #标记出选定基因的label
  geneList1 <- allDEG2[rownames(allDEG2) %in% i,]
  geneList1 <- subset(geneList1, select = -change)
  geneList1$label <- rownames(geneList1)
  #pdf("hotplot.pdf", width = 8, height = 10)
  volplot <- p + geom_label_repel(data = geneList1, 
                       aes(x = log2FoldChange, y = -log10(padj), label = label),
                       size = 4,color="black",
                       box.padding = unit(0.4, "lines"), 
                       segment.color = "black",   #连线的颜色
                       segment.size = 0.4,  #连线的粗细
  )
  png(paste("volcano_DESeq2_",i,".png"), width = 8, height = 10, units = "in", res = 800)
  print(volplot)
  dev.off()
}
```

## VENN图

```{r Venn, message=TRUE, warning=TRUE, include=FALSE}
#加载
library(VennDiagram)
#设置工作目录
setwd("E:/CRC")
#读取
data=read.table("TCGA.diff.Wilcoxon.txt", header=F, sep="\t", check.names=F)
Wilcoxon = data[,1]
data=read.table("ARG_gene.txt", header=F, sep="\t", check.names=F)
ARG = data[,1]

#画图
venn.diagram(x = list('ARG' = ARG,'Wilcoxon' = Wilcoxon),
             filename = 'VN.png',fill = c("darkorange1","green"))
#交集基因
intersectGenes = intersect(Wilcoxon,ARG)

write.table(file="intersectGenes.txt", intersectGenes, sep="\t", quote=F, col.names=F, row.names=F)
```


```{r VENN}